In [1]:
#Louis Colbert III
#M1 Assignment

# Sections are below under the "Section Headers"

In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('Datasets/datasets/data/housing.csv')

In [4]:
df.head(3)

,Neighborhood,Building.Classification,Total.Units,Year.Built,Gross.SqFt,Estimated.Gross.Income,Gross.Income.per.SqFt,Estimated.Expense,Expense.per.SqFt,Net.Operating.Income,Full.Market.Value,Market.Value.per.SqFt,Boro
0,FINANCIAL,R9-CONDOMINIUM,42,1920.0,36500,1332615,36.51,342005,9.37,990610,7300000,200.00,Manhattan
1,FINANCIAL,R4-CONDOMINIUM,78,1985.0,126420,6633257,52.47,1762295,13.94,4870962,30690000,242.76,Manhattan
2,FINANCIAL,RR-CONDOMINIUM,500,NaN,554174,17310000,31.24,3543000,6.39,13767000,90970000,164.15,Manhattan

In [5]:
type(df)

pandas.DataFrame

In [6]:
df.shape

(2626, 13)

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2626 entries, 0 to 2625
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Neighborhood             2626 non-null   str
 1   Building.Classification  2626 non-null   str
 2   Total.Units              2626 non-null   int64
 3   Year.Built               2530 non-null   float64
 4   Gross.SqFt               2626 non-null   int64
 5   Estimated.Gross.Income   2626 non-null   int64
 6   Gross.Income.per.SqFt    2626 non-null   float64
 7   Estimated.Expense        2626 non-null   int64
 8   Expense.per.SqFt         2626 non-null   float64
 9   Net.Operating.Income     2626 non-null   int64
 10  Full.Market.Value        2626 non-null   int64
 11  Market.Value.per.SqFt    2626 non-null   float64
 12  Boro                     2626 non-null   str
dtypes: float64(4), int64(6), str(3)
memory usage: 266.8 KB

In [8]:
df = df[['Boro', 'Building.Classification', 'Year.Built', 'Gross.SqFt', 'Full.Market.Value']]

In [9]:
df.head()

,Boro,Building.Classification,Year.Built,Gross.SqFt,Full.Market.Value
0,Manhattan,R9-CONDOMINIUM,1920.0,36500,7300000
1,Manhattan,R4-CONDOMINIUM,1985.0,126420,30690000
2,Manhattan,RR-CONDOMINIUM,NaN,554174,90970000
3,Manhattan,R4-CONDOMINIUM,1930.0,249076,67556006
4,Manhattan,R4-CONDOMINIUM,1985.0,219495,54320996

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2626 entries, 0 to 2625
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Boro                     2626 non-null   str
 1   Building.Classification  2626 non-null   str
 2   Year.Built               2530 non-null   float64
 3   Gross.SqFt               2626 non-null   int64
 4   Full.Market.Value        2626 non-null   int64
dtypes: float64(1), int64(2), str(2)
memory usage: 102.7 KB

In [11]:
df.Boro

0           Manhattan
1           Manhattan
2           Manhattan
3           Manhattan
4           Manhattan
            ...
2621    Staten Island
2622    Staten Island
2623    Staten Island
2624    Staten Island
2625    Staten Island
Name: Boro, Length: 2626, dtype: str

In [12]:
df.columns

Index(['Boro', 'Building.Classification', 'Year.Built', 'Gross.SqFt',
       'Full.Market.Value'],
      dtype='str')

In [13]:
df.iloc[0]

Boro                            Manhattan
Building.Classification    R9-CONDOMINIUM
Year.Built                         1920.0
Gross.SqFt                          36500
Full.Market.Value                 7300000
Name: 0, dtype: object

In [14]:
df_subset = df.iloc[2521:2541]

## Section 1

In [15]:
# Since python starts at 0 for the indexing using 2521 to 2541 as those are the true rows.

In [16]:
print(df_subset)

        Boro Building.Classification  Year.Built  Gross.SqFt  \
2521  Queens          R4-CONDOMINIUM      2006.0      111775
2522  Queens          R4-CONDOMINIUM      2005.0       93315
2523  Queens          R4-CONDOMINIUM      2005.0       82862
2524  Queens          R2-CONDOMINIUM      2005.0       27560
2525  Queens          R4-CONDOMINIUM      2009.0       48680
2526  Queens          R2-CONDOMINIUM      2007.0       98222
2527  Queens          R2-CONDOMINIUM      2006.0       53200
2528  Queens          R4-CONDOMINIUM      2005.0       74400
2529  Queens          R4-CONDOMINIUM      2005.0       41713
2530  Queens          R9-CONDOMINIUM      1986.0       82600
2531   Bronx          R2-CONDOMINIUM      1904.0       21092
2532   Bronx          R4-CONDOMINIUM      2006.0       72000
2533   Bronx          R4-CONDOMINIUM      2007.0      150121
2534   Bronx          R4-CONDOMINIUM      2007.0       63872
2535   Bronx          R4-CONDOMINIUM      2008.0      128643
2536   Bronx          R9-CONDOMINIUM      2005.0       99240
2537   Bronx          R9-CONDOMINIUM      2006.0       76984
2538   Bronx          R4-CONDOMINIUM      2005.0       24262
2539   Bronx          R2-CONDOMINIUM      1903.0        7745
2540   Bronx          R2-CONDOMINIUM      1909.0       14384

      Full.Market.Value
2521           10047997
2522            9062006
2523            7449028
2524            2158999
2525           16557010
2526            8501998
2527            4875001
2528            8412001
2529            4716002
2530            3003000
2531             653000
2532            4504003
2533            5854000
2534            2491000
2535            5017000
2536            3870000
2537            5304000
2538            1499988
2539             324000
2540             991003

## Section 2

In [18]:
df_subset.groupby('Boro')['Full.Market.Value'].mean()

Boro
Bronx     3050799.4
Queens    7478304.2
Name: Full.Market.Value, dtype: float64