## Name: Louis Colbert III
## Date: 2026-02-26
## Class: Programming 26SS_INFO_2648_WW

Program 2 (Chapter 2)

Use python to create your own dataset of an inventory list with at least 10 items. These items can be anything. If you can't think of anything then go to the grocery store or browse your Amazon wish list. Each item should have the following fields: Name (name of item), Description (a short description of the item), Type (i.e. food, clothing, car, software, camping, sports, etc), Quantity (number of items, Price (cost for a single item). For this assignment the price can be a whole number. It is not required to be a float integer,  but 2 thumbs up if it is.  

Output the entire dataframe with a new column that multiples the quantity with the price. The output should be displayed on screen and to a CSV file.

In [1]:
import pandas as pd

In [15]:
Name = ['Chicken', 'Ground Beef', 'Steak','Bologna', 'Cheese', 'Moscato', 'Ham', 'Oranges','Apples','Brocolini', 'Diapers', 'Wipes']
Description = ['poultry', 'cattle meat', 'Cruiseline meat shank', 'things people eat when theyre under the age of 12' , 'Queso','Wine', 'Pig meat',
              'fruit','fruit', 'veggies', 'adult XL super absorbency','Never dry spit induced wipes']
Type = ['frozen food', 'frozen food', 'frozen food', 'refridgerated food', 'refridgerated food', 'shelf stable', 'refridgerator food', 'produce', 
        'produce', 'produce', 'household items', 'household items']
Quantity = [5,11,33,53,4,344,56,997,223,45,56,98765]
Price = [2.33, 4.43, 8.99, .32,2.49,11.99,3.96,2.34,2.32,1.99,12.88, 3.33
        ]

In [16]:
Name = pd.Series(Name)

In [17]:
type(Name)

pandas.Series

In [18]:
Description = pd.Series(Description)

In [19]:
Type = pd.Series(Type)

In [20]:
Quantity = pd.Series(Quantity)

In [21]:
Price = pd.Series(Price)

In [22]:
grocery_list = pd.DataFrame(
    data = {
    'Name': Name,
    'Description': Description, 
    'Type': Type,
    'Quantity': Quantity,
    'Price': Price
} , 
    columns= ['Name','Description', 'Type', 'Quantity', 'Price']
)

In [23]:
grocery_list

,Name,Description,Type,Quantity,Price
0,Chicken,poultry,frozen food,5,2.33
1,Ground Beef,cattle meat,frozen food,11,4.43
2,Steak,Cruiseline meat shank,frozen food,33,8.99
3,Bologna,things people eat when theyre under the age of 12,refridgerated food,53,0.32
4,Cheese,Queso,refridgerated food,4,2.49
5,Moscato,Wine,shelf stable,344,11.99
6,Ham,Pig meat,refridgerator food,56,3.96
7,Oranges,fruit,produce,997,2.34
8,Apples,fruit,produce,223,2.32
9,Brocolini,veggies,produce,45,1.99
10,Diapers,adult XL super absorbency,household items,56,12.88
11,Wipes,Never dry spit induced wipes,household items,98765,3.33

In [24]:
grocery_list['Total'] = grocery_list['Quantity'] * grocery_list['Price']

In [25]:
grocery_list

,Name,Description,Type,Quantity,Price,Total
0,Chicken,poultry,frozen food,5,2.33,11.65
1,Ground Beef,cattle meat,frozen food,11,4.43,48.73
2,Steak,Cruiseline meat shank,frozen food,33,8.99,296.67
3,Bologna,things people eat when theyre under the age of 12,refridgerated food,53,0.32,16.96
4,Cheese,Queso,refridgerated food,4,2.49,9.96
5,Moscato,Wine,shelf stable,344,11.99,4124.56
6,Ham,Pig meat,refridgerator food,56,3.96,221.76
7,Oranges,fruit,produce,997,2.34,2332.98
8,Apples,fruit,produce,223,2.32,517.36
9,Brocolini,veggies,produce,45,1.99,89.55
10,Diapers,adult XL super absorbency,household items,56,12.88,721.28
11,Wipes,Never dry spit induced wipes,household items,98765,3.33,328887.45

In [26]:
grocery_list.to_csv('./data/grocery_list.csv')