## Course: 26SS INFO 2648 WW
## Name: Louis Colbert III
## Date: 2026-07-12
## Module 4

Datasets

fulfilment_center_info.csvDownload fulfilment_center_info.csv
meal_info.csvDownload meal_info.csv  
test.csvDownload test.csv
 

Program 

Write a program using the attached datasets above by doing the following:

1. Review the meal_info.csv and test.csv datasets and identify a common dataframe value (column name).
2. Merge the meal_info.csv and test.csv datasets using the common value. It will be the same for both datasets (right and left).
3. Review the fulfilment_center_info.csv and test.csv datasets and identify a common dataframe value (column name).
4. Merge the fulfilment_center_info.csv and test.csv datasets using the common value. It will be the same for both datasets (right and left).
5. Create a many-to-many merge by passing the multiple columns from the 2 merges above (#2 and #4). Use the 2 common values from the above merges to match to 2 columns for both right and left. Print only the 4th record of this merge. (Similar to pg. 106)

The 4th record of the many-to-many merge will look like the following:

In [3]:
#import statement for the data

import pandas as pd

In [4]:
#reading in the meals
meal = pd.read_csv("Datasets/datasets/data/meal_info.csv")

In [6]:
#reading in the test data
test = pd.read_csv("Datasets/datasets/data/test.csv")

In [8]:
#checking data
meal.head(3)

   meal_id   category cuisine
0     1885  Beverages    Thai
1     1993  Beverages    Thai
2     2539  Beverages    Thai

In [9]:
#checking data again
test.head(3)

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured
0,1028232,146,55,1885,158.11,159.11,0,0
1,1127204,146,55,1993,160.11,159.11,0,0
2,1212707,146,55,2539,157.14,159.14,0,0

In [12]:
#merging the datasets together on the meal_id
meal_cost = test.merge(meal, on="meal_id")

In [13]:
#checkiing data 
meal_cost.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,category,cuisine
0,1028232,146,55,1885,158.11,159.11,0,0,Beverages,Thai
1,1127204,146,55,1993,160.11,159.11,0,0,Beverages,Thai
2,1212707,146,55,2539,157.14,159.14,0,0,Beverages,Thai
3,1082698,146,55,2631,162.02,162.02,0,0,Beverages,Indian
4,1400926,146,55,1248,163.93,163.93,0,0,Beverages,Indian

In [15]:
#checking the columns 
meal_cost.info()

<class 'pandas.DataFrame'>
RangeIndex: 32573 entries, 0 to 32572
Data columns (total 10 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     32573 non-null  int64
 1   week                   32573 non-null  int64
 2   center_id              32573 non-null  int64
 3   meal_id                32573 non-null  int64
 4   checkout_price         32573 non-null  float64
 5   base_price             32573 non-null  float64
 6   emailer_for_promotion  32573 non-null  int64
 7   homepage_featured      32573 non-null  int64
 8   category               32573 non-null  str
 9   cuisine                32573 non-null  str
dtypes: float64(2), int64(6), str(2)
memory usage: 2.5 MB

In [16]:
#importing the fullfillment data
fulfilment = pd.read_csv("Datasets/datasets/data/fulfilment_center_info.csv")

In [17]:
fulfilment.head()

   center_id  city_code  region_code center_type  op_area
0         11        679           56      TYPE_A      3.7
1         13        590           56      TYPE_B      6.7
2        124        590           56      TYPE_C      4.0
3         66        648           34      TYPE_A      4.1
4         94        632           34      TYPE_C      3.6

In [18]:
#looking at test again since it is what the join will be on with the fullfulment
test

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured
0,1028232,146,55,1885,158.11,159.11,0,0
1,1127204,146,55,1993,160.11,159.11,0,0
2,1212707,146,55,2539,157.14,159.14,0,0
3,1082698,146,55,2631,162.02,162.02,0,0
4,1400926,146,55,1248,163.93,163.93,0,0
...,...,...,...,...,...,...,...,...
32568,1250239,155,61,1543,482.09,484.09,0,0
32569,1039516,155,61,2304,483.09,483.09,0,0
32570,1158107,155,61,2664,322.07,323.07,0,0
32571,1444235,155,61,2569,322.07,323.07,0,0
32572,1291286,155,61,2490,276.45,276.45,0,0

In [19]:
#merging on the fulfilment and the test data
center_test = pd.merge(test, fulfilment, on = "center_id")

In [20]:
#checking the dataset
center_test.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,city_code,region_code,center_type,op_area
0,1028232,146,55,1885,158.11,159.11,0,0,647,56,TYPE_C,2.0
1,1127204,146,55,1993,160.11,159.11,0,0,647,56,TYPE_C,2.0
2,1212707,146,55,2539,157.14,159.14,0,0,647,56,TYPE_C,2.0
3,1082698,146,55,2631,162.02,162.02,0,0,647,56,TYPE_C,2.0
4,1400926,146,55,1248,163.93,163.93,0,0,647,56,TYPE_C,2.0

In [21]:
#checking the other dataset
meal_cost.head()

,id,week,center_id,meal_id,checkout_price,base_price,emailer_for_promotion,homepage_featured,category,cuisine
0,1028232,146,55,1885,158.11,159.11,0,0,Beverages,Thai
1,1127204,146,55,1993,160.11,159.11,0,0,Beverages,Thai
2,1212707,146,55,2539,157.14,159.14,0,0,Beverages,Thai
3,1082698,146,55,2631,162.02,162.02,0,0,Beverages,Indian
4,1400926,146,55,1248,163.93,163.93,0,0,Beverages,Indian

### Creating the many to many relationship using the two different datasets and merging on the two columns centerid and mealid

In [29]:
many_merged_meals = meal_cost.merge(center_test, on = ["center_id", "meal_id"])

In [23]:
many_merged_meals.info()

<class 'pandas.DataFrame'>
RangeIndex: 309637 entries, 0 to 309636
Data columns (total 20 columns):
 #   Column                   Non-Null Count   Dtype
---  ------                   --------------   -----
 0   id_x                     309637 non-null  int64
 1   week_x                   309637 non-null  int64
 2   center_id                309637 non-null  int64
 3   meal_id                  309637 non-null  int64
 4   checkout_price_x         309637 non-null  float64
 5   base_price_x             309637 non-null  float64
 6   emailer_for_promotion_x  309637 non-null  int64
 7   homepage_featured_x      309637 non-null  int64
 8   category                 309637 non-null  str
 9   cuisine                  309637 non-null  str
 10  id_y                     309637 non-null  int64
 11  week_y                   309637 non-null  int64
 12  checkout_price_y         309637 non-null  float64
 13  base_price_y             309637 non-null  float64
 14  emailer_for_promotion_y  309637 non-null  int64
 15  homepage_featured_y      309637 non-null  int64
 16  city_code                309637 non-null  int64
 17  region_code              309637 non-null  int64
 18  center_type              309637 non-null  str
 19  op_area                  309637 non-null  float64
dtypes: float64(5), int64(12), str(3)
memory usage: 47.2 MB

In [27]:
many_merged_meals.head()

,id_x,week_x,center_id,meal_id,checkout_price_x,base_price_x,emailer_for_promotion_x,homepage_featured_x,category,cuisine,id_y,week_y,checkout_price_y,base_price_y,emailer_for_promotion_y,homepage_featured_y,city_code,region_code,center_type,op_area
0,1028232,146,55,1885,158.11,159.11,0,0,Beverages,Thai,1028232,146,158.11,159.11,0,0,647,56,TYPE_C,2.0
1,1028232,146,55,1885,158.11,159.11,0,0,Beverages,Thai,1262649,147,159.11,159.11,0,0,647,56,TYPE_C,2.0
2,1028232,146,55,1885,158.11,159.11,0,0,Beverages,Thai,1453211,149,157.14,158.14,0,0,647,56,TYPE_C,2.0
3,1028232,146,55,1885,158.11,159.11,0,0,Beverages,Thai,1262599,150,159.14,157.14,0,0,647,56,TYPE_C,2.0
4,1028232,146,55,1885,158.11,159.11,0,0,Beverages,Thai,1495848,151,160.11,159.11,0,0,647,56,TYPE_C,2.0

### Using iloc to print the 4th row in the many to many relationship

In [28]:
print(many_merged_meals.iloc[3])

id_x                         1028232
week_x                           146
center_id                         55
meal_id                         1885
checkout_price_x              158.11
base_price_x                  159.11
emailer_for_promotion_x            0
homepage_featured_x                0
category                   Beverages
cuisine                         Thai
id_y                         1262599
week_y                           150
checkout_price_y              159.14
base_price_y                  157.14
emailer_for_promotion_y            0
homepage_featured_y                0
city_code                        647
region_code                       56
center_type                   TYPE_C
op_area                          2.0
Name: 3, dtype: object